package com.csw.android.videofloatwindow.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.csw.android.videofloatwindow.entities.VideoInfo;
import com.csw.android.videofloatwindow.entities.PlaySheet;
import com.csw.android.videofloatwindow.entities.PlaySheetVideo;

import com.csw.android.videofloatwindow.greendao.VideoInfoDao;
import com.csw.android.videofloatwindow.greendao.PlaySheetDao;
import com.csw.android.videofloatwindow.greendao.PlaySheetVideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoInfoDaoConfig;
    private final DaoConfig playSheetDaoConfig;
    private final DaoConfig playSheetVideoDaoConfig;

    private final VideoInfoDao videoInfoDao;
    private final PlaySheetDao playSheetDao;
    private final PlaySheetVideoDao playSheetVideoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoInfoDaoConfig = daoConfigMap.get(VideoInfoDao.class).clone();
        videoInfoDaoConfig.initIdentityScope(type);

        playSheetDaoConfig = daoConfigMap.get(PlaySheetDao.class).clone();
        playSheetDaoConfig.initIdentityScope(type);

        playSheetVideoDaoConfig = daoConfigMap.get(PlaySheetVideoDao.class).clone();
        playSheetVideoDaoConfig.initIdentityScope(type);

        videoInfoDao = new VideoInfoDao(videoInfoDaoConfig, this);
        playSheetDao = new PlaySheetDao(playSheetDaoConfig, this);
        playSheetVideoDao = new PlaySheetVideoDao(playSheetVideoDaoConfig, this);

        registerDao(VideoInfo.class, videoInfoDao);
        registerDao(PlaySheet.class, playSheetDao);
        registerDao(PlaySheetVideo.class, playSheetVideoDao);
    }
    
    public void clear() {
        videoInfoDaoConfig.clearIdentityScope();
        playSheetDaoConfig.clearIdentityScope();
        playSheetVideoDaoConfig.clearIdentityScope();
    }

    public VideoInfoDao getVideoInfoDao() {
        return videoInfoDao;
    }

    public PlaySheetDao getPlaySheetDao() {
        return playSheetDao;
    }

    public PlaySheetVideoDao getPlaySheetVideoDao() {
        return playSheetVideoDao;
    }

}
