package com.csw.android.videofloatwindow.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.csw.android.videofloatwindow.entities.PlaySheetVideo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PLAY_SHEET_VIDEO".
*/
public class PlaySheetVideoDao extends AbstractDao<PlaySheetVideo, Long> {

    public static final String TABLENAME = "PLAY_SHEET_VIDEO";

    /**
     * Properties of entity PlaySheetVideo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property PlaySheetId = new Property(1, long.class, "playSheetId", false, "PLAY_SHEET_ID");
        public final static Property VideoInfoId = new Property(2, long.class, "videoInfoId", false, "VIDEO_INFO_ID");
    }


    public PlaySheetVideoDao(DaoConfig config) {
        super(config);
    }
    
    public PlaySheetVideoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PLAY_SHEET_VIDEO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"PLAY_SHEET_ID\" INTEGER NOT NULL ," + // 1: playSheetId
                "\"VIDEO_INFO_ID\" INTEGER NOT NULL );"); // 2: videoInfoId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PLAY_SHEET_VIDEO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PlaySheetVideo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getPlaySheetId());
        stmt.bindLong(3, entity.getVideoInfoId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PlaySheetVideo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getPlaySheetId());
        stmt.bindLong(3, entity.getVideoInfoId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public PlaySheetVideo readEntity(Cursor cursor, int offset) {
        PlaySheetVideo entity = new PlaySheetVideo( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // playSheetId
            cursor.getLong(offset + 2) // videoInfoId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PlaySheetVideo entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setPlaySheetId(cursor.getLong(offset + 1));
        entity.setVideoInfoId(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PlaySheetVideo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PlaySheetVideo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PlaySheetVideo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
